title: MathPeat INI Network
description: A UK research network on soft porous materials

theme: jekyll-theme-cayman

plugins:
  - jekyll-relative-links
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

include:
  - index.md

# Optional, only if your theme supports navigation
navigation:
  - title: Home
    url: index.md
  - title: Activities
    url: activities.md
  - title: Get Involved
    url: get-involved.md
  - title: Resources
    url: resources.md
  - title: Blog
    url: blog/