title: MathPeat INI Network
description: A UK research network on soft porous materials
url: "https://multiform-uon.github.io"
baseurl: "/mathpeat"

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""  # Applies to all files
    values:
      layout: default
      title: MathPeat INI Network

plugins:
  - jekyll-relative-links
  - jekyll-feed

relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - style.css
  - mathpeat.jpg

# Optional, only if your theme supports navigation
navigation:
  - title: Home
    url: index.md
  - title: Activities
    url: activities.md
  - title: Get Involved
    url: get-involved.md
  - title: Resources
    url: resources.md
  - title: Blog
    url: blog/
