title: MathPeat INI Network
description: "A research network on the mathematics of peatlands and porous media"
baseurl: ""     # set if deploying to subpath
url: "https://yourusername.github.io"  # or your site URL
theme: minima
# Optional: to include your CSS overrides
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include extra files
include:
  - assets/css/style.css